### ISSUE TITLE
If mimalloc is built with MI_OSX_INTERPOSE=OFF MI_OSX_ZONE=OFF, realpath test case in test-api is broken

### ISSUE THREAD

**Issue by barracuda156** [microsoft/mimalloc#778]
The failure confirmed on macOS Ventura (x86_64) and Snow Leopard (ppc).
See: https://github.com/macports/macports-ports/pull/19357?notification_referrer_id=NT_kwDOBXwLlrM2OTk0NjU1NzU2OjkyMDE1NTEw#issuecomment-1627030209

It seems to fail here:
```
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x96d19b68
0x00023b3c in _mi_free_generic ()
(gdb) where
#0  0x00023b3c in _mi_free_generic ()
#1  0x0002c720 in mi_heap_realpath () at _string.h:80
#2  0x00004ed4 in main ()
```

**Comment by barracuda156** [comment]
I will need to try with the current version
