### ISSUE TITLE
Shutdown issues using heap bound to arena, `mi_collect`

### ISSUE THREAD

**Issue by biddisco** [microsoft/mimalloc#828]
We have a custom arena which needs to be thread safe, we allocate memory (with `mmap`) and use
```
bool success = mi_manage_os_memory_ex(ptr, size, true, false, true, numa_node, true, &m_arena_id);
```
In our allocator, we store a `thread local` heap ptr to access it, and this appears to work fine
```
    if (!thread_local_ex_mimalloc_heap)
    {
        thread_local_ex_mimalloc_heap = mi_heap_new_in_arena(m_arena_id);
    }
    ... // later when allocating etc
    rtn = mi_heap_malloc_aligned(thread_local_ex_mimalloc_heap, size, alignment);
```
If we use MI_SKIP_COLLECT_ON_EXIT  a simple test program that generates N threads, make a load of allocations and deallocations behaves completely as expected, but if we enable `mi_collect` to run on exit, then on shutdown we have a segfault when pages are 'cleaned up' (?)
```
1  std::__atomic_base<mi_segment_s *>::load  atomic_base.h  820  0x7ffff7f69f39 
2  std::atomic<mi_segment_s *>::load         atomic         578  0x7ffff7f69f39 
3  std::atomic_load_explicit<mi_segment_s *> atomic         1324 0x7ffff7f69e45 
4  mi_abandoned_pop                          segment.c      1195 0x7ffff7f6852d 
5  _mi_abandoned_reclaim_all                 segment.c      1384 0x7ffff7f6927a 
6  mi_heap_collect_ex                        heap.c         138  0x7ffff7f57ce6 
7  mi_heap_collect                           heap.c         178  0x7ffff7f57e7e 
8  mi_collect                                heap.c         182  0x7ffff7f57ea6 
9  mi_process_done                           init.c         633  0x7ffff7f5a585 
10 __cxa_finalize                            cxa_finalize.c 83   0x7ffff7845a56 
```
The error is triggered in `segment.c` when `mi_abandoned_pop` tries to get the 'next' segment from the abandoned list(?) 
```
      mi_segment_t* anext = mi_atomic_load_ptr_relaxed(mi_segment_t, &segment->abandoned_next);
```
Now if we look at the value of th segment pointer, it points to our custom arena memory allocation (in this case segment points to `0x7fffd4000000` which from printf and inspection, I know is the base address of our custom memory arena allocation
```
		anext	@0x7ffff7e39440	mi_segment_t
		next	0	mi_tagged_segment_t
		segment	0x7fffd4000000	mi_segment_t*
		ts	140736750161921	mi_tagged_segment_t
```

If we simply do not delete our own custom arena memory on shutdown (`munmap`), the segfault goes away - because now the seegment is a valid address and all is well. We can also enable `MI_SKIP_COLLECT_ON_EXIT` to hide the problem - but it seems to me that this is a bug in mimalloc - segments from custom arenas, should not be moved to the primary heap at any time for cleanup operations - they should remain owned and managed only in the heaps bound to those arenas.

Have I misunderstood whats going on, and can we fix our code some other way. Thanks.

**Comment by biddisco** [comment]
Bump: Looking at this again after a long delay, and hoping for some comment from mimalloc maintainers as to the correct fix

**Comment by biddisco** [comment]
Looking again at this problem. Question (@daanx ?): When an arena is destroyed, how can I remove all segments that have come from it from the global abandoned list? The dereferencing of a value stored in a segment whose backing memory has already been deleted
https://github.com/microsoft/mimalloc/blob/14b4f674fa2cff00f28333365fe07ce916575c30/src/arena-abandon.c#L214
triggers segfaults on shutdown. I've tried calling `mi_heap_collect(heap, true);` when each heap is destroyed, but this does not do the job. Any hints on how to ensure the abandoned segments are removed before the backing memory is freed?

**Comment by alexgarciaparadox** [comment]
is this still an issue?

**Comment by biddisco** [comment]
The problem still exists if that's what you are asking.  I ran a quick test and see this
```
Thread 1 "test_host" received signal SIGSEGV, Segmentation fault.
0x00007ffff7f52812 in mi_arena_segment_clear_abandoned_at (arena=0x7ffff7f8bf00 <mi_arena_static>, subproc=0x7ffff7f8cf80 <mi_subproc_default>, bitmap_idx=0) at /home/biddisco/src/pinned_mimalloc/extern/mimalloc/src/arena-abandon.c:214
214       mi_assert_internal(mi_atomic_load_relaxed(&segment->thread_id) == 0);
(gdb) bt
#0  0x00007ffff7f52812 in mi_arena_segment_clear_abandoned_at (arena=0x7ffff7f8bf00 <mi_arena_static>, subproc=0x7ffff7f8cf80 <mi_subproc_default>, bitmap_idx=0)
    at /home/biddisco/src/pinned_mimalloc/extern/mimalloc/src/arena-abandon.c:214
#1  0x00007ffff7f52ad9 in mi_arena_segment_clear_abandoned_next_field (previous=0x7fffffff82d0) at /home/biddisco/src/pinned_mimalloc/extern/mimalloc/src/arena-abandon.c:265
#2  0x00007ffff7f52d51 in _mi_arena_segment_clear_abandoned_next (previous=0x7fffffff82d0) at /home/biddisco/src/pinned_mimalloc/extern/mimalloc/src/arena-abandon.c:320
#3  0x00007ffff7f6be6d in _mi_abandoned_reclaim_all (heap=0x7ffff7f8a880 <_mi_heap_main>, tld=0x7ffff7f894a0 <tld_main+32>)
    at /home/biddisco/src/pinned_mimalloc/extern/mimalloc/src/segment.c:1325
#4  0x00007ffff7f58c2d in mi_heap_collect_ex (heap=0x7ffff7f8a880 <_mi_heap_main>, collect=MI_FORCE) at /home/biddisco/src/pinned_mimalloc/extern/mimalloc/src/heap.c:148
#5  0x00007ffff7f58dc3 in mi_heap_collect (heap=0x7ffff7f8a880 <_mi_heap_main>, force=true) at /home/biddisco/src/pinned_mimalloc/extern/mimalloc/src/heap.c:192
#6  0x00007ffff7f5bc57 in mi_process_done_once () at /home/biddisco/src/pinned_mimalloc/extern/mimalloc/src/init.c:699
#7  0x00007ffff7f5bd05 in mi_process_done () at /home/biddisco/src/pinned_mimalloc/extern/mimalloc/src/init.c:728
#8  0x00007ffff7f5bd3b in _mi_auto_process_done () at /home/biddisco/src/pinned_mimalloc/extern/mimalloc/src/init.c:734
#9  0x00007ffff7f71a9a in mi_process_detach () at /home/biddisco/src/pinned_mimalloc/extern/mimalloc/src/prim/prim.c:45
#10 0x00007ffff7fc924e in _dl_fini () at ./elf/dl-fini.c:142
#11 0x00007ffff7445495 in __run_exit_handlers (status=0, listp=0x7ffff761a838 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true)
    at ./stdlib/exit.c:113
#12 0x00007ffff7445610 in __GI_exit (status=<optimized out>) at ./stdlib/exit.c:143
#13 0x00007ffff7429d97 in __libc_start_call_main (main=main@entry=0x4055b6 <main()>, argc=argc@entry=1, argv=argv@entry=0x7fffffff8658) at ../sysdeps/nptl/libc_start_call_main.h:74
#14 0x00007ffff7429e40 in __libc_start_main_impl (main=0x4055b6 <main()>, argc=1, argv=0x7fffffff8658, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffff8648) at ../csu/libc-start.c:392
#15 0x00000000004054f5 in _start ()
```
on shutdown - goes away when the skip collect flag is set
